import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Exact flat names from code.html ──────────────────────────
        "secondary":                  "#ffb694",
        "secondary-fixed-dim":        "#ffb694",
        "surface-container-lowest":   "#1e0707",
        "surface-dim":                "#240c0c",
        "on-surface":                 "#ffdad8",
        "secondary-container":        "#ff6a00",
        "primary-container":          "#b11226",
        "surface":                    "#240c0c",
        "on-tertiary-fixed":          "#271900",
        "inverse-primary":            "#b91a2b",
        "on-primary-fixed-variant":   "#93001a",
        "on-error-container":         "#ffdad6",
        "on-tertiary":                "#422c00",
        "on-surface-variant":         "#e3bebc",
        "inverse-on-surface":         "#462827",
        "on-primary-container":       "#ffc1be",
        "on-secondary":               "#571f00",
        "inverse-surface":            "#ffdad8",
        "surface-bright":             "#503130",
        "primary":                    "#ffb3b0",
        "on-primary":                 "#68000f",
        "primary-fixed":              "#ffdad8",
        "on-tertiary-fixed-variant":  "#5f4100",
        "error-container":            "#93000a",
        "tertiary-fixed":             "#ffdeaa",
        "background":                 "#240c0c",
        "on-error":                   "#690005",
        "on-secondary-fixed":         "#351000",
        "error":                      "#ffb4ab",
        "outline-variant":            "#5b403f",
        "secondary-fixed":            "#ffdbcc",
        "surface-container-highest":  "#4b2d2b",
        "surface-container-high":     "#3f2221",
        "surface-container-low":      "#2e1413",
        "surface-variant":            "#4b2d2b",
        "outline":                    "#aa8987",
        "tertiary-container":         "#765200",
        "on-background":              "#ffdad8",
        "tertiary-fixed-dim":         "#f6bd54",
        "on-secondary-container":     "#571f00",
        "surface-container":          "#331817",
        "tertiary":                   "#f6bd54",
        "on-primary-fixed":           "#410006",
        "primary-fixed-dim":          "#ffb3b0",
        "on-secondary-fixed-variant": "#7b2f00",
        "surface-tint":               "#ffb3b0",
        "on-tertiary-container":      "#ffc662",
      },
      fontFamily: {
        // ── Names used in code.html class names ───────────────────────
        "headline-lg-mobile": ["var(--font-anton)", "sans-serif"],
        "headline-lg":        ["var(--font-anton)", "sans-serif"],
        "display-hero":       ["var(--font-anton)", "sans-serif"],
        "headline-md":        ["var(--font-anton)", "sans-serif"],
        "body-md":            ["var(--font-be-vietnam)", "sans-serif"],
        "body-lg":            ["var(--font-be-vietnam)", "sans-serif"],
        "label-caps":         ["var(--font-space-grotesk)", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["48px",  { lineHeight: "52px",  letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-lg":        ["64px",  { lineHeight: "72px",  letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-hero":       ["120px", { lineHeight: "110px", letterSpacing: "-0.04em", fontWeight: "400" }],
        "headline-md":        ["32px",  { lineHeight: "40px",  fontWeight: "400" }],
        "body-lg":            ["20px",  { lineHeight: "32px",  fontWeight: "300" }],
        "body-md":            ["16px",  { lineHeight: "24px",  fontWeight: "400" }],
        "label-caps":         ["12px",  { lineHeight: "16px",  letterSpacing: "0.1em",  fontWeight: "700" }],
      },
      spacing: {
        "section-gap":    "160px",
        "gutter":         "24px",
        "unit":           "8px",
        "margin-desktop": "80px",
        "margin-mobile":  "24px",
        "container-max":  "1440px",
      },
      borderRadius: {
        none:    "0",
        sm:      "0.125rem",
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      animation: {
        "breathe":     "breathe 8s ease-in-out infinite",
        "float":       "float 6s ease-in-out infinite",
        "pulse-glow":  "pulse-glow 2s ease-in-out infinite",
        "ping":        "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      },
      keyframes: {
        breathe: {
          "0%, 100%": { transform: "scale(1)" },
          "50%":      { transform: "scale(1.05)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%":      { transform: "translateY(-20px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "1",   boxShadow: "0 0 20px rgba(177,18,38,0.4)" },
          "50%":      { opacity: "0.8", boxShadow: "0 0 40px rgba(177,18,38,0.6)" },
        },
        ping: {
          "75%, 100%": { transform: "scale(2)", opacity: "0" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
